/**
 * ContentOS - Production & Media Planning Domain Models & Contracts
 * 
 * Defines the structured specification for translating scripts into production-ready
 * scene blueprints, visual asset requirements, audio requirements, timed captions,
 * and asset checklists.
 * 
 * Note: Represents requirements for production; does NOT imply assets have been generated yet.
 */

import { PlatformType } from './content';
import { ScriptFormat, ScriptSourceReference } from './script';

export type AssetStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'not_required';

export type AspectRatio = '9:16' | '16:9' | '1:1' | '4:5';

export type VisualType =
  | 'talking_head'
  | 'screen_recording'
  | 'code_visual'
  | 'chart'
  | 'diagram'
  | 'kinetic_text'
  | 'b_roll'
  | 'stock_style'
  | 'generated_image'
  | 'generated_video'
  | 'simple_background';

export type VisualAssetType =
  | 'background_image'
  | 'overlay_image'
  | 'video_clip'
  | 'b_roll_clip'
  | 'chart_graphic'
  | 'code_snippet_card'
  | 'diagram';

export type AudioAssetType =
  | 'voiceover'
  | 'background_music'
  | 'sound_effect'
  | 'ambient';

/**
 * Detailed requirement specification for a visual asset to be generated downstream
 */
export interface VisualAssetRequirement {
  id: string;
  scene_id: string;
  asset_type: VisualAssetType;
  description: string;
  prompt: string;
  aspect_ratio: AspectRatio;
  resolution: string; // e.g. "1080x1920"
  duration_seconds: number;
  source: 'ai_generated' | 'template_rendered' | 'screen_capture' | 'stock';
  generation_required: boolean;
  status: AssetStatus;
  content_asset_id?: string;
  storage_path?: string;
  notes?: string;
}

/**
 * Detailed requirement specification for an audio asset to be synthesized or selected downstream
 */
export interface AudioAssetRequirement {
  id: string;
  scene_id?: string;
  audio_type: AudioAssetType;
  description: string;
  text?: string; // Text to be spoken if voiceover
  voice_requirement?: string; // e.g. "Authoritative, natural pace, clear US tech tone"
  duration_seconds: number;
  generation_required: boolean;
  status: AssetStatus;
  storage_path?: string;
  content_asset_id?: string;
  notes?: string;
}

/**
 * Timed caption block aligned to speech segments
 */
export interface CaptionBlock {
  id: string;
  scene_id: string;
  start_second: number;
  end_second: number;
  text: string;
  emphasis_words: string[];
}

/**
 * Single actionable item in the asset checklist
 */
export interface AssetChecklistItem {
  id: string;
  asset_id: string;
  category: 'visual' | 'audio' | 'overlay' | 'caption';
  requirement: string;
  status: AssetStatus;
  generation_required: boolean;
  notes?: string;
}

/**
 * A discrete production scene mapped directly from a script section
 */
export interface ProductionScene {
  id: string;
  order: number;
  start_second: number;
  end_second: number;
  duration_seconds: number;
  purpose: string;
  spoken_text: string;
  visual_type: VisualType;
  visual_prompt: string;
  b_roll_requirement: string;
  camera_direction: string;
  composition: string;
  on_screen_text?: string;
  caption_text: string;
  source_references: ScriptSourceReference[];
  visual_assets: VisualAssetRequirement[];
  audio_assets: AudioAssetRequirement[];
  captions: CaptionBlock[];
}

/**
 * Comprehensive Production Package deliverable generated by the Production Agent
 */
export interface ProductionPackage {
  id?: string;
  project_id: string;
  job_id?: string;
  script_id?: string;
  platform: PlatformType;
  format: ScriptFormat;
  duration_seconds: number;
  aspect_ratio: AspectRatio;
  scenes: ProductionScene[];
  narration_segments: AudioAssetRequirement[];
  visual_assets: VisualAssetRequirement[];
  audio_assets: AudioAssetRequirement[];
  overlays: Array<{
    id: string;
    scene_id: string;
    text: string;
    style: 'headline' | 'stat_callout' | 'quote' | 'badge';
    start_second: number;
    end_second: number;
  }>;
  captions: CaptionBlock[];
  transitions: Array<{
    from_scene_order: number;
    to_scene_order: number;
    transition_type: 'cut' | 'crossfade' | 'zoom_in' | 'slide_left' | 'whip_pan';
    duration_seconds: number;
  }>;
  asset_checklist: AssetChecklistItem[];
  production_notes: string[];
  unresolved_requirements: string[];
  confidence: 'low' | 'medium' | 'high';
  generated_at: string;
  version: number;
  is_mock_data: boolean;
}
