/**
 * ContentOS - Research Domain & Provider Contracts
 */

export type ResearchPriority = 'low' | 'medium' | 'high';
export type ResearchConfidence = 'low' | 'medium' | 'high';
export type SourceRelevance = 'low' | 'medium' | 'high';
export type SourceCredibility = 'low' | 'medium' | 'high';

export type ResearchSourceType =
  | 'article'
  | 'paper'
  | 'news'
  | 'documentation'
  | 'report'
  | 'mock_test_fixture';

/**
 * Phase A: Structured Research Plan generated by Gemini
 */
export interface ResearchPlan {
  research_questions: string[];
  claims_to_verify: string[];
  facts_needed: string[];
  source_requirements: string[];
  freshness_requirements: string;
  research_priority: ResearchPriority;
}

/**
 * An individual evidence source gathered during research retrieval
 */
export interface ResearchSource {
  title: string;
  url: string;
  publisher: string;
  published_at?: string;
  retrieved_at: string;
  source_type: ResearchSourceType;
  relevance: SourceRelevance;
  credibility: SourceCredibility;
  evidence_summary: string;
}

/**
 * Specific verified claim linked to evidence
 */
export interface ResearchEvidence {
  claim: string;
  source: string;
  supporting_excerpt: string;
  confidence: ResearchConfidence;
  notes?: string;
}

/**
 * Complete consolidated research deliverable for downstream scripting
 */
export interface ResearchPackage {
  plan: ResearchPlan;
  sources: ResearchSource[];
  evidence: ResearchEvidence[];
  unresolved_questions: string[];
  overall_confidence: ResearchConfidence;
  isMockData?: boolean;
}

/**
 * Result returned by the research retrieval provider (Phase B)
 */
export interface ResearchRetrievalResult {
  provider: string;
  sources: ResearchSource[];
  evidence: ResearchEvidence[];
  unresolved_questions: string[];
  overall_confidence: ResearchConfidence;
  isMockData: boolean;
}
